---
apiVersion: MachineDeployment
kind: MachineDeployment
metadata:
  name: .*
  labels:
    cluster.x-k8s.io/cluster-name: "usw2-cluster2"
    nodepool: "usw2-c2-nodepool0"
spec:
  selector:
    matchLabels:
        cluster.x-k8s.io/cluster-name: "usw2-cluster2"
        nodepool: "usw2-c2-nodepool0"
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: "usw2-cluster2"
        nodepool: "usw2-c2-nodepool0"
